version: "3.9"

services:
  app:
    image: expense-tracker:latest
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app
    ports:
      - "8080:8080"
#    environment:
#      SPRING_PROFILES_ACTIVE: "prod"
      # Example DB configs (optional)
      # SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/mydb
      # SPRING_DATASOURCE_USERNAME: user
      # SPRING_DATASOURCE_PASSWORD: pass
#    depends_on:
#      - db
    restart: always

#  db:
#    image: mysql:8.4
#    container_name: mysql-db
#    environment:
#      MYSQL_ROOT_PASSWORD: root
#      MYSQL_DATABASE: mydb
#      MYSQL_USER: user
#      MYSQL_PASSWORD: pass
#    ports:
#      - "3306:3306"
#    volumes:
#      - mysql_data:/var/lib/mysql
#    restart: always
#
#volumes:
#  mysql_data:
